resource_types:
  - name: android-sdk-resource
    type: docker-image
    source: {repository: xaethos/android-sdk-resource}

resources:
  - name: android-sdk-linux
    type: android-sdk-resource
    source:
      components:
        - tools

jobs:
  - name: try-resource
    plan:
      - get: android-sdk-linux
      - task: list-sdk
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ubuntu}
          inputs:
            - name: android-sdk-linux
          run:
            path: find
            args: ["android-sdk-linux"]
