resources:
  - name: android-sdk-fastlane-resource
    type: git
    source:
      uri: https://github.com/eyedol/android-sdk-fastlane-resource.git
      branch: master

  - name: android-sdk-fastlate-resource-image
    type: docker-image
    source:
      repository: eyedol/android-sdk-fastlane-resource
      username: {{docker-username}}
      password: {{docker-password}}

jobs:
  - name: build
    plan:
      - get: android-sdk-fastlane-resource
      - put: android-sdk-fastlane-resource-image
        params:
          build: android-sdk-fastlane-resource
